# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: install
        run: |
          npm install
          npm run build
          cd dist
          git init
          git config user.name junilhwang
          git config user.email junil.h@kakao.com
          git remote add origin https://github.com/JunilHwang/js-subway-admin
          git remote set-url origin https://junilhwang:${{ secrets.GITHUB_TOKEN }}@github.com/junilhwang/js-subway-admin
          git add .
          git commit -m "deploy"
          git checkout -b gh-pages
          git push origin +gh-pages

